### ISSUE TITLE
Using /ip 127.0.0.1 causing windows desktop client to crash.

### ISSUE THREAD

**Issue by jackdh** [SEEDTEAM/jack-telegram-bot#28]
As mentioned in the title using the command '/ip 127.0.0.1' causes the windows desktop client to auto close.

Messages must be deleted via another medium such as mobile to fix the issue.

**Comment by TiagoDanin** [comment]
Wrong place...
You should be looking for this https://github.com/telegramdesktop/tdesktop/issues/new

**Comment by TiagoDanin** [comment]
Thank you... :) 
Hope that the telegram correct this error.
It was added a system to avoid new errors.
