### ISSUE TITLE
chat stats not showing all stats

### ISSUE THREAD

**Issue by arieljannai** [SEEDTEAM/jack-telegram-bot#36]
Hi,

I've checked the `chatstats` of Jack, and noticed it is giving stats only from the moment he joined the group chat.
Is it possible to get stats on all the history?
I know that new users in chat can see all the history (supergroup - all, regular - 300). It's not the same with bot? it doesn't have access to earlier messages?

Thanks,
Ariel

**Comment by TiagoDanin** [comment]
Bot for telegram no has access the historic.

**Comment by Imandaneshi** [comment]
Bots only have access to msgs since they joined the chat

**Comment by arieljannai** [comment]
Maybe it's possible to suggest it to telegram - to add an option to give access to all previous messages (like allowing access when adding to group).
Do you know someone at telegram that it's possible to suggest it to?
